### ISSUE TITLE
Unbox should create `.local/share/unbox/meta` if it doesn't exist

### ISSUE THREAD

**Issue by spencergilbert** [lopukhov/unbox#12]
If `.local/share/unbox/meta` doesn't exist, `unbox` fails to create toolboxes when trying to write the the TOML file into the directory.

`unbox` can gracefully handle this by create the directory if missing.

Note: toolboxes created prior to the meta files may not be `rm`-able by `unbox` because of the missing file. They can be dropped by `rm -rf`ing the image directory.

**Comment by lopukhov** [comment]
Good catch! Should be fixed in latest commit
