### ISSUE TITLE
enhancement: Improve `unbox list` UX

### ISSUE THREAD

**Issue by spencergilbert** [lopukhov/unbox#7]
Today if no toolboxes have been created `unbox list` doesn't output anything.

```shell
unbox on  main is 📦 v0.2.0 via 🦀 v1.63.0 
❯ unbox list

unbox on  main is 📦 v0.2.0 via 🦀 v1.63.0 
❯ 

```

Compared to:

```shell
unbox on  main is 📦 v0.2.0 via 🦀 v1.63.0 
❯ unbox list
alpine
```

I think it would be nicer to either report that no toolboxes were found, perhaps prompting the user to run `unbox create`. Another direction would be following something like `podman` (or `toolbox`) and provide some more context.

```shell
unbox on  main is 📦 v0.2.0 via 🦀 v1.63.0 
❯ podman image list
REPOSITORY                TAG         IMAGE ID      CREATED      SIZE
docker.io/library/alpine  latest      9c6f07244728  4 weeks ago  5.83 MB

unbox on  main is 📦 v0.2.0 via 🦀 v1.63.0 took 21s 
❯ toolbox list
IMAGE ID      IMAGE NAME                                    CREATED
1942cc76c9c8  registry.fedoraproject.org/fedora-toolbox:33  11 months ago

CONTAINER ID  CONTAINER NAME     CREATED         STATUS      IMAGE NAME
9a9467bcf170  fedora-toolbox-33  24 seconds ago  configured  registry.fedoraproject.org/fedora-toolbox:33
```

Perhaps something like:

```shell
❯ unbox list
IMAGE NAME                       NAME    CREATED
docker.io/library/alpine:latest  alpine  4 weeks ago
```

`unbox` could write some metadata about the toolbox, source, age, etc. either in the created rootfs or in a small storage file. `toolbox` leverages `podman` (IIRC) to list, based on image tags so `unbox` would need to manage it's own data here.

**Comment by lopukhov** [comment]
Yes, I had in mind something similar.

My idea is to set a toml metadata file when creating a toolbox with default data such as:
- Preferred shell
- Mount points
- Maybe the hostname

In that case the `list` subcommand should print a table (maybe with [tabled](https://crates.io/crates/tabled)) with that information. The `run` and `create` subcommands should read from the metadata file to set mount points and such.

I also like the idea of prompting the user to create a toolbox when there are no toolboxes.

In the future another subcommand could be added to be able to modify the metadata file.
