### ISSUE TITLE
enhancement: `unbox create`

### ISSUE THREAD

**Issue by spencergilbert** [lopukhov/unbox#8]
As mentioned in the README:

> ...note that it may take a while if the image has not already been downloaded...

It'd improve the UX to provide some feedback during the process, if only a spinner showing that the program hasn't stalled.

**Comment by lopukhov** [comment]
I like the idea. I think we could do it using [indicatif](https://crates.io/crates/indicatif), but if you have another idea I am open to suggestions.

I am going to give priority to the bugs that made some images not usable, so if you want open (another) PR for this enhancement

:smile:
